### ISSUE TITLE
Change WCAG WG to AG WG

### ISSUE THREAD

**Issue by Ryladog** [w3c/dpubwg-charter#13]
In 4.1 W3C Groups
The **Web Content Accessibility Guidelines Working Group** NAME has been changed by the W3C to the **Accessibility Guidelines Working Group**.

Fix typo (shold to should):
"That Working Group is responsible for the development of WCAG; the Digital Publishing Working Group shold work together with that Working Group to ensure the inclusion of publication specific features. "

**Comment by iherman** [comment]
Thanks @Ryladog
