### ISSUE TITLE
Addressing "editorial note" for 3.2

### ISSUE THREAD

**Issue by lrosenthol** [w3c/dpubwg-charter#17]
>This whole section should be discussed on whether we would go down that path at all.

Let's determine what to do and either remove it (my preference) or not.

**Comment by iherman** [comment]
Discussed on the call of 2017-02-27 and was decided to remove it

**Comment by iherman** [comment]
For the records: relevant minutes on the decision are at: https://www.w3.org/2017/02/27-dpub-minutes.html#mozTocId462950

**Comment by iherman** [comment]
Change happened on 2017-02-28, see commit https://github.com/w3c/dpubwg-charter/commit/a6991aeca4deae7fe2e627243b7091dc7cd9c69a
