### ISSUE TITLE
Use the W3C Software and Document license

### ISSUE THREAD

**Issue by iherman** [w3c/dpubwg-charter#21]
Issue raised on behalf of Chris Lilley (@svgeesus) on the mailing list

> I strongly suggest changing to the  [W3C Software and Document license](https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document). This is the same as the [document license](https://www.w3.org/Consortium/Legal/2015/doc-license) (for the actual document text) and the same as the software license for examples, code snippets etc which is important as the Document License *forbids copying or modifying examples*. And we want people to be able to do that.

**Comment by iherman** [comment]
Note: the current choice was not based on any discussion, it was just copy-pasted from other places.

**Comment by GarthConboy** [comment]
Agreed, change will be made.
