### ISSUE TITLE
Coordination details with the CSS WG

### ISSUE THREAD

**Issue by iherman** [w3c/dpubwg-charter#22]
Issue raised on behalf of Chris Lilley (@svgeesus) on the mailing list

> The current text "A number of features described in the Web Publication UCR document (e.g., personalization) may require new CSS functionalities " is true, but says nothing about coordination. Is the expectation that new capabilities are developed in the DPubWG? Developed jointly? Developed by providing UC&R and asking CSS WG to develop them? Something else?
Also, could DPubWG help CSS WG in the development and testing of existing and new capabilities that are needed by Digital Publishing.

**Comment by dauwhe** [comment]
Suggested text:

>New CSS features may be needed to support web publications. Such features would be specified in the CSS Working Group, with the Publishing Working Group providing use cases, requirements, and examples. The Publishing Working Group would also help the CSSWG with the development and testing of new and existing CSS functionality that is of interest to the publishing community. There will likely be several people who are members of both groups, and thus can serve as liaisons.

**Comment by iherman** [comment]
Sounds good to me. 

I would wait at least a day before incorporating it, unless I get a massive amount of +1-s right now:-)

Thanks!

**Comment by laudrain** [comment]
+1
Luc


De : Ivan Herman <notifications@github.com<mailto:notifications@github.com>>
Répondre à : w3c/dpubwg-charter <reply@reply.github.com<mailto:reply@reply.github.com>>
Date : mardi 14 mars 2017 15:59
À : w3c/dpubwg-charter <dpubwg-charter@noreply.github.com<mailto:dpubwg-charter@noreply.github.com>>
Cc : Subscribed <subscribed@noreply.github.com<mailto:subscribed@noreply.github.com>>
Objet : Re: [w3c/dpubwg-charter] Coordination details with the CSS WG (#22)


Sounds good to me.

I would wait at least a day before incorporating it, unless I get a massive amount of +1-s right now:-)

Thanks!

**Comment by mattgarrish** [comment]
Minor nit, but the last sentence sounds unsure of itself for a charter. Could it be reconstructed to make liaisons more of a recognized need? Maybe: "The group will designate liaisons to work with the CSS WG on issues, as needed."

**Comment by iherman** [comment]
@mattgarrish, I take your point but maybe I would combine the two:

> New CSS features may be needed to support web publications. Such features would be specified in the CSS Working Group, with the Publishing Working Group providing use cases, requirements, and examples. The Publishing Working Group would also help the CSS WG with the development and testing of new and existing CSS functionality that is of interest to the publishing community. The group will designate liaisons to work with the CSS WG on issues as needed, and who will likely be part of both groups.

WDYT?

**Comment by mattgarrish** [comment]
That works for me.

**Comment by mattgarrish** [comment]
If you want to make me really happy, maybe s/likely/ideally/. :)

But I can live with the proposed wording.

**Comment by iherman** [comment]
Added a Pull Request #34. @mattgarrish, it is my goal to make you really happy:-)

**Comment by GarthConboy** [comment]
SGTM

Best,
    Garth
