### ISSUE TITLE
Consider optimal WG name (perhaps "Web Publications Working Group")

### ISSUE THREAD

**Issue by whmccoy** [w3c/dpubwg-charter#26]
The scope of proposed WG charter focuses solely on Web Publications and is based on "Web Publications" supporting documents (use cases & requirements and vision). It is anticipated that the new W3C Publishing Business Group will take on the responsibility for being a conduit between publishing industry and other W3C WGs that is presently part of the scope of the Digital Publishing Interest Group. Therefore it might be cleaner to name the new WG the "Web Publications Working Group". This might help make it more clear to prospective participants what is being worked on in the WG, as well as help make the new WG more attractive to participants who don't necessarily come from traditional publishing industry or think of themselves in working in "digital publishing" per se since that term has come to mean, for some, eBooks. 

Or perhaps there is a better name. I am just raising the issue that we shouldn't just presume the name is optimal but think it through.

**Comment by GarthConboy** [comment]
Agreed at March 13th DG meeting:

Publishing Working Group
