### ISSUE TITLE
Motivate need for EPUB 4 in the charter

### ISSUE THREAD

**Issue by whmccoy** [w3c/dpubwg-charter#27]
It has been observed that the draft charter focuses on the motivation for Web Publicaitons and doesn't explicitly motivate **why** we need an EPUB 4 **now** (with "now"  being understood in the context of the expected timeline of developing W3C Recommendations to mean "within the next several years"). This motivation should be added along with, perhaps, suitable fuzziness about whether there are going to be three things specified (Web Publications, Portable Web Publications that are packaged, and EPUB4 that is also packaged but has a more specific and EPUB3-compatible profile) or just 2 things (Web Publications and a packaged instantiation we call EPUB 4) or maybe only 1 thing (Web Publications) - TBD after the WG kicks off.

**Comment by therealglazou** [comment]
I would handle this as a Business Case to be written by the BG, explaining why work on the future of publications is needed, and only refer to that document from the WG Charter. So this is a new document, most probably short, on BG's radar.

**Comment by lrosenthol** [comment]
The thinking to date, on the "number of things" is 3 - just as listed in the Charter.

- WP, address the needs for publications within the "normal" context of the web.
- PWP, address the overall issues encountered with packaged OWP content (with a focus on those that comply with WP)
- EPUB 4, provide a PWP-compliant version of EPUB that also addresses EPUB3 compatibility.

**Comment by iherman** [comment]
For the records: the separate document, and the reference from the text, has been discussed, and decided upon, in a separate mailing list discussion. See the [corresponding thread](https://lists.w3.org/Archives/Public/public-publishingbg/2017Mar/0021.html).
