### ISSUE TITLE
Need to add a Liaison to the EPUB CG.

### ISSUE THREAD

**Issue by GarthConboy** [w3c/dpubwg-charter#29]
Title says it all.

**Comment by GarthConboy** [comment]
The same should also be true to the Publishing Business Group.

**Comment by iherman** [comment]
> On 13 Mar 2017, at 16:16, GarthConboy <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> Title says it all.
> 
> —
> 

Actually, the same should be true for the Publishing BG!

**Comment by GarthConboy** [comment]
As it does in the preceding comment!  :-)
