### ISSUE TITLE
Mission statement still boilerplate text

### ISSUE THREAD

**Issue by WSchindler** [w3c/dpubwg-charter#35]
The **mission statement** ("The mission of the Publishing Working Group is to [do something cool and specific on the Web]." currently has a boilerplate text. 

Should that stand for a link to a separate document or is it just a placeholder for text to be written? 

Section 1 **Goals** nicely describes the intended convergence of traditional (electronic) publishing and the Web. Should this introduction thus be a kind of abstract of Section 1?

**Comment by iherman** [comment]
> The mission statement ("The mission of the Publishing Working Group is to [do something cool and specific on the Web]." currently has a boilerplate text.
> 
> Should that stand for a link to a separate document or is it just a placeholder for text to be written?
> 
> Section 1 Goals nicely describes the intended convergence of traditional (electronic) publishing and the Web. Should this introduction thus be a kind of abstract of Section 1?
> 

Exactly as you say: it should be some sort of an abstract of the rest. TBD.

Ivan

**Comment by rickj** [comment]
Closed by #52
