### ISSUE TITLE
Minor editorial issue: use of ampersand in EPUB&3.1

### ISSUE THREAD

**Issue by WSchindler** [w3c/dpubwg-charter#40]
I just stumbled over "EPUB&3.1" which is used twice in Section 3.1, EPUB 4. Is this a typo that should correctly be written as "EPUB 3.1" or does it have a special meaning I don't know yet?

**Comment by iherman** [comment]
> 
> I just stumbled over "EPUB&3.1" which is used twice in Section 3.1, EPUB 4. Is this a typo that should correctly be written as "EPUB 3.1" or does it have a special meaning I don't know yet?
> 

Ouch, again… For some reason, the &nbsp; (which is what I tried to put there) got transformed into a &amp; by… I am not sure. I wish there was an easy way to type a non breaking space and one would not be forced to use the XML entity instead…

Will take care of this right away.
