### ISSUE TITLE
Reference to Latinreq in the charter

### ISSUE THREAD

**Issue by iherman** [w3c/dpubwg-charter#42]
(This is just a reminder) As agreed on the [IG call of 2017-03-20](https://www.w3.org/2017/03/20-dpub-minutes.html) latinreq will also be listed as a possible WG Note published by this WG. 

Cc: @dauwhe

**Comment by murata2makoto** [comment]
I have a question.  There are several [requirement documents](https://www.w3.org/International/layout) from the W3C I18N WG, where latinreq is one of them.  [ International text layout and typography index](http://w3c.github.io/typography/)   from the I18N WG is particularly important.   What is the relationship between this group and the I18N WG?

**Comment by iherman** [comment]
@murata0204,

the specific liaisons to the I18N Working and Interest Groups are not explicitly called out; see the statement at the very beginning of section 4.

> For all specifications, this Working Group will seek horizontal review for accessibility, internationalization, performance, privacy, and security with the relevant Working and Interest Groups, and with the TAG.

and, for reasons of succinctness, these are not called out in the list because, per W3C process, such reviews of, say, I18N MUST happen in any case.

Do you believe that we should have more explicit liaison statement in the list? I am not fundamentally opposed to it just that, as an editor of the chart, I try to be mindful of the size of the document...

Latinreq is a slightly different issue; that document is owned by the Publishing Interest Group, so if this group disappears in favour of the Publishing Working Group, we need a new home for it...

@r12a, any opinion on this?

**Comment by r12a** [comment]
I think there are a couple of possibilities here. I haven't searched out the background.

1. If the charter lists lreq as a deliverable of the group, that's fine. It would be nice to see progress on it, and that should help.
2. If lreq is referenced just as a source of requirements, then it's not fine to ignore the other documents.

**Comment by iherman** [comment]
> On 27 Mar 2017, at 15:08, r12a <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> I think there are a couple of possibilities here. I haven't searched out the background.
> 
> If the charter lists lreq as a deliverable of the group, that's fine. It would be nice to see progress on it, and that should help.
> If lreq is referenced just as a source of requirements, then it's not fine to ignore the other documents.


The idea is the former, as agreed on our latest call. I am still waiting for the proper terminology to be used in the charter

@dauwhe <https://github.com/dauwhe> ?

**Comment by iherman** [comment]
@dauwhe, the reference has been added in https://github.com/w3c/dpubwg-charter/commit/26c266ce076fce1783babcf854e7f8828130ed39 ; please review and close the issue if this is fine.

**Comment by dauwhe** [comment]
The proposed text works for me. I seem to be unable to close issues in this repo, but feel free to close.

**Comment by iherman** [comment]
Thanks @dauwhe, closing.
