### ISSUE TITLE
If DRM is mentioned at all, legal uses of content should also be mentioned

### ISSUE THREAD

**Issue by jar398** [w3c/dpubwg-charter#43]
Without prejudice concerning whether DRM should be in scope, the draft currently puts it *in* scope, lightly, with the comment "the Working Group shouldn’t make any design decision that would make such features impossible" (belying the section's title).

*If* there is language like that for DRM, then there should also be parallel language regarding legal use of content, such as reproduction of public domain or open access works, and exercise of fair use and related rights. That is, something like: "the Working Group shouldn’t make any design decision that would make legal reproduction or exercise of fair use rights impossible".

**Comment by iherman** [comment]
(purely administrative comment)

@jar398, would you mind adding this comment to issue #15 and close this issue? I am a little bit concerned about the duplication of issues on the same topic, and your comment seems to be a direct reaction on https://github.com/w3c/dpubwg-charter/issues/15#issuecomment-286103338

Thank you
