### ISSUE TITLE
Clarify references to Web App Manifests, Service Workers

### ISSUE THREAD

**Issue by joeberkovitz** [w3c/dpubwg-charter#44]
It would provide more clarity if the references to some of the more recent specs included very short summaries of what aspects of the specs are relevant.

Web App Manifests could easily be confused with the now-deprecated Cache Manifests and perhaps this should be called out.

Service Workers are still not widely understood as a vehicle for creating offline apps, so it's worth saying this.

**Comment by iherman** [comment]
@joeberkovitz can you look at https://github.com/w3c/dpubwg-charter/pull/45 to see if that works for you?

Thanks

**Comment by iherman** [comment]
Closed by virtue of #45.
