### ISSUE TITLE
Editorial review of the WG charter

### ISSUE THREAD

**Issue by bfoleary** [w3c/dpubwg-charter#46]
At the March 13 meeting of the Publishing BG, I agreed to review the WG charter and suggest editorial changes. That's what this note covers.

Amend the first sentence to read "The mission of the Publishing Working Group is to provide the technical specifications that will make publications first-class entities on the Web." [this is drawn from subsequent document text]

In the section on meeting schedule, upper-case 'W' to start the sentence ('We')

**Section 1 Goals**
first para, last sentence, add a hyphen: 'page-based media'
second para, first sentence, and 'and': 'manga, notebooks, and albums...'
fourth para, first sentence, add a hyphen: 'should become first-class entities ...'

**Section 2 Scope**
first para, first sentence, lower-case a: 'For the purpose of this document, a web publication...'
first para, second sentence: delete the dash and add a period, so that it reads: 'A Web Publication is not just a collection of links. The act of publishing involves ...'
first para, current third sentence, add a comma after 'Thus' and delete the one after WP: 'Thus, the publisher provides an origin for the WP and a URL...'
first para, last sentence, add a hyphen to 'high-level' and delete the semi-colon after 'characteristics'

first bulleted item, add 'it may': 'A Web Publication may be portable, and _it may_ be hosted ...'
second bulleted item, break up the second sentence to read: 'The package must include the unique identifier of the manifestation. A Web Publication's origin is essential information if it is to become portable.
fourth bulleted item, second sentence: 'Users should, as much as possible...'
sixth bulleted item, add a hyphen: 'a range of meta-information including...'
sixth bulleted item, first sub-bullet: 'table of contents'
sixth bulleted item, third sub-bullet: 'metadata such as author(s), title, and unique identification.'

**Section 2.1 Input Documents**
Bulleted item that starts with "EPUB 3.1". Change the first sentence to read 'The Member Submission of EPUB 3 will be an important input into Web Publications, ...'

Question: Subsequent section 3.1 mentions 'EPUB 3 Structural Semantics Vocabulary' as a resource. Should it be added to this section with a more detailed explanation?

**Section 2.2  Out of Scope**
First bulleted item: '(however, the Working Group should not make any design decisions that ...'

**Section 2.3 Success Criteria**
Third para, change first sentence to read: 'Each specification should contain a section describing: known impacts on accessibility for users with disabilities; ways the specification features address those impacts; and recommendations for minimizing accessibility problems in implementation.'

**Section 3.1 Deliverables**
Section on EPUB 4, change last sentence to read: 'This specification should generally be a functional superset of EPUB 3.1. Functionally round-tripping to/from EPUB 3.1 is considered highly desirable.'

Section on DPUB-ARIA Module 2.0, first sentence, add a hyphen: '... coverage of publication-related terms.'

**Section 3.2 Other Deliverables**
Last sentence, add a hyphen: 'inclusion of publication-specific features'

**Section 3.3 Milestones**
First bulleted item: Date not included; amend to just June 2017.
Subsequent bulleted items: Suggest explaining the acronyms used (FPWD, CR, REC), as the charter will be circulated to the publishing community, some of whom will not know the terms (I am one of those people).

**Section 4 Coordination**
First paragraph, spell out 'Technical Architecture Group' at the initial mention. Suggest doing the same with FPWD and CR, if not explained in section 3.3

**Section 4.1 W3C Groups**
Web Platform Working Group, first bullet, amend to read: '_Web App Manifests_ may be the basis for specifying (table of contents, metadata, etc.) provided by a Web Publication.'
Web Platform Working Group, second bullet, amend to read: '_Service Workers_ may become the fundamental building block for the implementation and testing of Web Applications.'
Web Platform Working Group, third bullet, amend to read: '_Packaging on the Web_ (jointly developed with the TAG) may provide a way of packaging for the purpose of Packaged Web Publications.'

CSS Working Group, change last sentence to read: 'The group will designate liaisons to work with the CSS WG on issues as needed. Liaisons will ideally be part of both groups.'

EPUB 3 Community Group, change first sentence to read: 'While working on EPUB 3-related projects, the EPUB 3 Community Group may surface technical concerns, requirements, and issues that are also relevant to the work of the Publishing Working Group.'

Publishing Business Group, second sentence, make 'requirements' plural.

**Section 4.2 External Organizations**
For the Book Industry Study Group, change the description to read: 'This group currently maintains the EPUB 3 Support Grid, which provides information n reading-system support for EPUB 3. This tool may be extended to track support for WP in general and EPUB 4 in particular.

**Section 5 Participation**
No changes proposed.

**Section 6 Communication**
First para, second sentence, add language: '...on a public repository, and the drafts may permit direct public contribution requests.'
Third para, change to read: 'Most Publishing Working Group teleconferences will focus on discussion of particular specifications. The calls will be conducted on a weekly basis.'
Fourth para, delete the colon after 'technical work'

**Section 7 Decision Policy**
First para, second sentence, add a period after 'other reviewers.' Delete 'and' and Capitalize 'Consensus'
Second para, change the end to read '... may call for a group vote, recording a decision along with any objections.'
Third para, add 'obtained': '... the resolution will be considered to have obtained consensus as a resolution of the Working Group.'
Fifth para, add a period after 'Votes)': (Section 3.4 Votes). It includes no voting procedures beyond ...'

Remaining sections (8, 9 and 10)
No changes proposed.

**Comment by iherman** [comment]
Thank you @bfoleary. I have incorporated all the changes; I have only three minor remarks:

- The mission statement is still to be finalized (see also issue #35) but I agree that your change is welcome for the time being. Done.

- Your comment on the structural semantics: you are absolutely right, I have added a separate entry for this among the input documents.

- The 'Out of Scope' on DRM has changed a lot, and the current text will definitely not stay as is. I have not changed that section.
