### ISSUE TITLE
Reference to BFF

### ISSUE THREAD

**Issue by iherman** [w3c/dpubwg-charter#48]
(Just a reminder issue) a proper reference to the BFF work of the IDPF EPUB WG is still missing.

Cc: @dauwhe

**Comment by HadrienGardeur** [comment]
I'm not entirely sure that there's something stable to reference purely for BFF.

**Comment by lrosenthol** [comment]
@HadrienGardeur should we remove the reference then?

**Comment by mattgarrish** [comment]
The IDPF didn't formally publish anything, but there are google docs from the 3.1 revision that deal with the browser/server friendly manifestation: the [use cases and requirements](https://docs.google.com/document/d/1ZTBiSyyIgQMXh_9Ubtep4I7TfW6Yu6l8e06-9EKaNQU/edit#heading=h.v0la5426mf86) and a [subgroup document](https://docs.google.com/document/d/1nXd8xMsNOA7sdwudpO2KS_L0Hc-0SxYx1ScrGIhRBBg/edit#) that lists ideas along with telcon minutes.

I guess it depends on what you're looking for from the reference whether either of the two is worth referencing.

**Comment by HadrienGardeur** [comment]
The subgroup document is IMO replaced by what Readium has produced at this point. The Use Cases and Requirements could be useful, I'll let @iherman decide.

It's possible also that @dauwhe would like to reference the proposal about using strictly HTML, but I'll let hime chime in on that.

**Comment by TzviyaSiegman** [comment]
@dauwhe is traveling, and this should eait until he returns.

**Comment by mattgarrish** [comment]
@HadrienGardeur Sure, I was only responding to the "work of the IDPF EPUB WG" part of what Ivan wrote. The WG never formally resumed the work beyond those docs.

**Comment by iherman** [comment]
I have the impression that, in this case, we should remove this reference from the list. I would wait until @dauwhe's return, of course.

@HadrienGardeur I have not checked, but I would expect that the Use case document has a large overlaps with the UCR document published by the DPUB IG. It also looks like a working document (lots of comments open, etc), which may not look right as an input document to a charter.

**Comment by dauwhe** [comment]
I'm fine with not having a specific reference to BFF in the charter.
