### ISSUE TITLE
Final version of the 'mission' statement

### ISSUE THREAD

**Issue by iherman** [w3c/dpubwg-charter#49]
This is more of an administrative step: I have accepted pull request #47 to allow others to comment on a version of the charter that is as final as possible. There was one minor issue on that text, reproduced in this comment.

**Comment by iherman** [comment]
Reproducing the comment of @jar398  (https://github.com/w3c/dpubwg-charter/pull/47#issuecomment-290222047) here

---

Much better - it gets rid of the problem with "publication" and helps a lot with "web publication" since its definition is moved to a less high-profile position.

The last line still doesn't say what it means:

> In short, “publications”—with all their specificities and traditions—should become first-class entities on the Web

As written this makes no sense since many publications (e.g. articles in the New York Times) already are first class entities on the Web - it can't be stated categorically. I think the dashed part needs to be turned into a qualifier, a restrictive clause instead of a nonrestrictive one, since you're only talking about certain publications that are not already first class on the Web.

**Comment by iherman** [comment]
@jar398, the current text says (as a reaction on your comment):

> In short, <em>digital versions of traditional publications—with all their specificities and traditions—should become first-class entities on the Web</em>.

Does that work for you?

**Comment by iherman** [comment]
Note that this text (probably the last paragraph) could become the overall mission statement of the charter, thereby answering to the issue raised in #35, too.

**Comment by pbelfanti** [comment]
How about just adding "all", as in "In short, all publications - with their specificities and traditions- should become first-class citizens on the web." That acknowledges that some publications already are, but some are not and need to be.

**Comment by iherman** [comment]
I like that!

**Comment by iherman** [comment]
@pbelfanti @jar398 : I have modified the text per @pbelfanti's comment.
