### ISSUE TITLE
Is "origin" used as in web security?

### ISSUE THREAD

**Issue by wseltzer** [w3c/dpubwg-charter#50]
In Web Application Security, "origin" is a defined term with specific meaning for security boundaries (the same-origin policy, see https://tools.ietf.org/html/rfc6454

If that's not the sense meant here in the scope section, could you use a different term?

**Comment by lrosenthol** [comment]
Yes, the use of term origin in the scope is meant in the sense of web
application security.

**Comment by iherman** [comment]
Ah! @lrosenthol if this is indeed the case (you are the security expert:-) maybe we should add a reference to make it clear. I am on a call right now; can you change the text to include that?

Thanks

**Comment by iherman** [comment]
Actually... @lrosenthol @wseltzer : I have just added a link to the word 'origin', linking to the RFC itself. If you think this is fine, could you simply close this issue?

**Comment by lrosenthol** [comment]
That change is perfect - thanks, @iherman.
