### ISSUE TITLE
Is "uniquely identify" per-work or per-copy?

### ISSUE THREAD

**Issue by wseltzer** [w3c/dpubwg-charter#51]
Since per-copy unique identifiers would raise privacy concerns, please clarify the use of "uniquely identifiable".

**Comment by laudrain** [comment]
Later in that paragraph, the text  says "The act of publishing involves obtaining resources and organizing them into a publication, which must be “manifested” by having files on a Web server. Thus the publisher provides an origin for the WP, and **a URL that can uniquely identify that manifestation**."
Refering to the library concept of manifestation in FRBR model, that unique identifier doesn't identify "per work" neither "per copy". Its usage would be equivalent as the one of an ISBN for a paper book.

**Comment by iherman** [comment]
@wseltzer @laudrain : would it be o.k. if, for the purpose of avoiding misunderstanding, we would make the word 'manifestation' a link to the FRBR concept? @wseltzer, I believe that, from a security point of view a FRBR 'work' and a FRBR 'manifestation' is the same; the privacy issue my come up if we were talking about the identification of a singular copy.

@laudrain which is the authoritative reference for FRBR? Is https://archive.ifla.org/VII/s13/frbr/frbr1.htm#3.2 the right one?

**Comment by laudrain** [comment]
**@iherman** : Yes I think it is the good one.

**Comment by iherman** [comment]
Ok. The full sentence now says:

> Thus the publisher provides an <a href="https://tools.ietf.org/html/rfc6454">origin</a> for the WP, and a URL that can uniquely identify that <a href="https://archive.ifla.org/VII/s13/frbr/frbr1.htm#3.2">(FRBR) manifestation</a>.

@wseltzer , does that work for you? If yes, the issue can also be closed.

**Comment by iherman** [comment]
Closing, in agreement with @wseltzer
