### ISSUE TITLE
Reference to WCAG and WAI...

### ISSUE THREAD

**Issue by iherman** [w3c/dpubwg-charter#54]
(Filing this on behalf of Judy Brewer)

> I note this phrase: "This includes general WCAG and WAI requirements of the W3C" and suggest that given the subject matter you might want to replace it with:  "This includes W3C WCAG 2.0 or later, and ATAG 2.0 requirements."

**Comment by iherman** [comment]
@avneeshsingh, could you look at this?

**Comment by avneeshsingh** [comment]
As per principles, I am fine with the suggestion. Some considerations:
- If we are going for list of standards, what about other W3C accessibility standards like UAAG?
- On the lines of WCAG 2.0 and later do we need to say ATAG 2.0 and later and so on?

**Comment by iherman** [comment]
@avneeshsingh, I am not sure UAAG is relevant for this Working Group. We are dealing with the format level issues, which affects WCAG, obviously. Even ATAG is a bit of a stretch, actually, although some of the issues may affect the way authoring work so I can see some reasons for it. But how user agent operates is beyond the scope of this WG in my view.

What about:

> "This includes requirements of W3C WCAG 2.0 or ATAG 2.0 (or later versions)."

**Comment by avneeshsingh** [comment]
Looks fine. We are mainly concerned with WCAG, and authoring tool guidelines can accompany the text. 
The reading systems work related to epubtest.org may go in some other W3C group.
So, this issue can be closed.
