### ISSUE TITLE
Add early reference to coordination with other W3C Groups

### ISSUE THREAD

**Issue by swickr** [w3c/dpubwg-charter#57]
Re-reading this draft top-to-bottom with (marginally) fresh eyes, it occurs to me that new readers may not realize the full import of the words in 1. Goals ".. to provide the necessary technologies on the Open Web Platform to ...". 

Specifically, as clarified later in section 4, this Working Group must work with other W3C Working Groups to collectively provide the necessary technologies; i.e. this WG augments already-chartered work on the Open Web Platform.

I suggest augmenting the first sentence in the second paragraph of Goals to read "... to provide, in concert with other W3C Groups as outlined in Section 4.1, the necessary technologies to ..."

**Comment by iherman** [comment]
+1. Will take care of this in a few.

**Comment by swickr** [comment]
I didn't mean for you to drop some of the existing text in that sentence, sorry.  I was proposing it read

> It is the goal of the Publishing Working Group to provide, in concert with other W3C Groups as outlined in <a href="#w3c-coordination">Section&nbsp;4.1</a>, the necessary technologies on the Open Web Platform to make the combination of traditional publishing and the Web complete in terms of the readers’ needs, portability, distribution, archiving, offline access, or reliable cross referencing.

**Comment by iherman** [comment]
Ah. I misunderstood.
