### ISSUE TITLE
Editorial nits

### ISSUE THREAD

**Issue by swickr** [w3c/dpubwg-charter#58]
A couple of small fixes to polish this:

2. Scope
2nd bullet, 3rd sentence: "... if it is to become/-s-/ portable."
6th bullet: "... to a range /+of+/ meta-information ..."

3. Deliverables, EPUB 4: "... to/from EPUB 3.1 /+is+/ considered ..."

2.3 Success Criteria,
4. Coordination,
6. Communication,
7. Decision Policy
Several Process Document links in these sections are to an out-of-date dated version; please change them to use the Latest operative version URI.

**Comment by iherman** [comment]
+1 taking care of these in a few

**Comment by iherman** [comment]
The comment in https://github.com/w3c/dpubwg-charter/commit/ae67370086d9d86874d4bf1a789624f13e1dccda is wrong; it took care of this issue. Closing.

**Comment by swickr** [comment]
I think it's better to use the "Latest operative" URI rather than yet another dated URI, but at least the 2017 Process URI is better than what had been there.  Thanks.

**Comment by iherman** [comment]
Actually... I am not even sure. Who knows how the process document will change in two years? At that time the WG (hopefully:-) will still be around, but the charter may become problematic...

E.g., when I made the change there was a URI that had, originally, an extra path that is now folded into the process document, so you need only a fragid. :-(
