### ISSUE TITLE
best practices and primers for content authors?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/dpubwg-charter#59]
In 3.2, the third bullet reads:

> Primers or Best Practice documents to support web developers when designing applications.

Isn't it possible that we'll develop the same for content authoring? Accessibility best practices being one area we might consider as we coordinate for inclusion in AG, for example.

In any case, it might be helpful to be more flexible here with wording like: "Primers or Best Practice documents to support content authors and application developers."

**Comment by iherman** [comment]
+1. Will take care of it in a few.
