### ISSUE TITLE
Update goals section to match current text in PWP document

### ISSUE THREAD

**Issue by lrosenthol** [w3c/dpubwg-charter#6]
this is based on some older text - let's get it up to date

**Comment by GarthConboy** [comment]
This should have been done in Ivan's latest proposed draft t be discussed Monday.  Right, Ivan?

**Comment by iherman** [comment]
(@lrosenthol: Admin proposal: can we close this issue and keep only #7, referring both scope and goals? I think we can all agree that a consistency with the DPUB draft is essential, we can track that in one single issue... If you agree, can you close this and rename the other one?)

**Comment by lrosenthol** [comment]
Yes that's fine..  Will do.
