### ISSUE TITLE
Clarify discussion of "the other origin" making choices

### ISSUE THREAD

**Issue by jyasskin** [w3c/dpubwg-charter#61]
https://w3c.github.io/dpubwg-charter/#scope has:

> A Web Publication may be portable, and it may be hosted at some other origin. However, it must preserve information about its original origin and identity, so that references to a portable copy can be reconciled with the original publication, and so that the other origin can make informed choices about how much trust to grant to the publication.

What does it mean for the "other origin" to make choices about how much trust to grant? I suspect you meant that the browser or user loading content from origin 2 needs to be able to make informed choices about whether to trust the content as if it came from origin 1.

**Comment by iherman** [comment]
That is indeed the intention. How about

> A Web Publication may be portable, and it may be hosted at some other origin. However, it must preserve information about its original origin and identity, so that references to a portable copy can be reconciled with the original publication, and so that the user (or user agent) of the other origin can make informed choices about how much trust to grant to the publication, just as if it was referring to the original origin.

**Comment by jyasskin** [comment]
That's clearer, yes. Thanks.

**Comment by iherman** [comment]
Thanks, will do the change in a few minutes.

**Comment by iherman** [comment]
Closing by virtue of https://github.com/w3c/dpubwg-charter/commit/5a76dadef2f5861ecf7868d42018eab24ed33ef4
