### ISSUE TITLE
pwp-ucr lists requirements, but many are already covered by open web specs

### ISSUE THREAD

**Issue by jyasskin** [w3c/dpubwg-charter#62]
The [charter](https://w3c.github.io/dpubwg-charter/#goals) is incorrect to say that
> the “[Web Publications Use Cases and Requirements](https://www.w3.org/TR/pwp-ucr/)” document, published by the Digital Publishing Interest Group, lists a number of use cases and requirements that are not yet covered by the current environments based on the Open Web Platform.

For example:
1. https://www.w3.org/TR/pwp-ucr/#unique-identifier is provided by URLs.
1. https://www.w3.org/TR/pwp-ucr/#onloffl is now provided by service workers.
1. https://www.w3.org/TR/pwp-ucr/#reading-order is provided by <link rel="next">.
1. https://www.w3.org/TR/pwp-ucr/#escalating_trust is provided by permission requests.
1. etc.

I'd be unhappy if the scope included re-inventing these bits of the web just because they appear in the requirements document. Would it be possible to put the full list of unsolved requirements in the scope document, and be clear that the "Use Cases and Requirements" doc is just informative?

**Comment by mac2net** [comment]
Offline is not solved by device workers let's again be 100% clear.
Service Workers is a cache.

**Comment by iherman** [comment]
@jyasskin, you are that some of the requirements may indeed be covered by current features; in this sense, the sentence is misleading and it must be changed. On the other hand, I don't believe it is the job of the charter to decide which of the UCR items are or are not covered but the charter and which are; there may be some details needing further adjustment or further details on how exactly to use them. Would the formulation below work for you?

> the “Web Publications Use Cases and Requirements” document, published by the Digital Publishing Interest Group, lists a number of use cases and requirements for publications on the Web. It will be the task of the Working Group to identify those requirements that are not yet fully covered by the current environments based on the Open Web Platform, and would therefore need further work.

**Comment by jyasskin** [comment]
That's definitely an improvement.

I'd like to see something that constrains the group to re-use as much existing stuff as practical. Is that already somewhere in the Scope section?

**Comment by iherman** [comment]
There is, at present, no explicit text and, though that is clearly the intention, I agree it is worth emphasizing.

What I would propose to extend the section above making this explicit. The whole section reads now (on my machine that, it is not committed) as follows:

>... the <a href="https://www.w3.org/TR/pwp-ucr/">“Web Publications Use Cases and Requirements”</a> document, published by the <a href="https://www.w3.org/dpub/IG/">Digital Publishing Interest Group</a>, lists a number of use cases and requirements for publications on the Web.
> It will be the task of the Working Group to identify those requirements that are not yet fully covered by the current environments based on the Open Web Platform, and would therefore need further work, while re-using existing technologies developed by other Working Groups as much as possible and practical.

WDYT?

**Comment by jyasskin** [comment]
That looks great, thanks!

**Comment by iherman** [comment]
Closing by virtue of https://github.com/w3c/dpubwg-charter/commit/151c23bb10e89cfa24859a9b3c5161a90a7e329a
