### ISSUE TITLE
Update Scope and Goals sections to reflect state of PWP draft

### ISSUE THREAD

**Issue by lrosenthol** [w3c/dpubwg-charter#7]
As per #6 , we should the latest text

**Comment by GarthConboy** [comment]
This should have been done in Ivan's latest proposed draft t be discussed Monday.  Right, Ivan?

**Comment by iherman** [comment]
I agree that there is a need for consistency, and we should update this text when we get to an equilibrium point on the PWP draft (at least the relevant sections). The current text reflects the status of the PWP text at the time of writing. (With only editorial changes.)

**Comment by lrosenthol** [comment]
Updated title as per discussion with @iherman

**Comment by iherman** [comment]
The PWP definition part is already done, but further discussion on, eg, offline/online should be pursued.

**Comment by iherman** [comment]
Done now.
