### ISSUE TITLE
EPUB compatibility is not a requirement of PWP, only of the EPUB4 profile

### ISSUE THREAD

**Issue by lrosenthol** [w3c/dpubwg-charter#8]
Remove or rewrite "Compatibility with EPUB 3 will be a consideration in development of all three specifications"

**Comment by GarthConboy** [comment]
I'm not sure I would count "will be a consideration" as meaning "is a requirement".  :-)

It (EPUB 3 compatibility) is, indeed, not a requirement of "WP", but it is a requirement (or at least consideration) of "P" (or one of the "P"s).

**Comment by GarthConboy** [comment]
Well, actually, being able to represent the core functionality of EPUB 3 (e.g., expression of a linear reading order over a collection of resources) in WP is interesting.

**Comment by lrosenthol** [comment]
> being able to represent the core functionality of EPUB 3 (e.g., expression of a linear reading order over a collection of resources) in WP is interesting

I expect that many concepts from EPUB will make their way into PWP, but not
in a syntax compatible manner

**Comment by iherman** [comment]
I tried to be non-committal with the text "will be a consideration", and I am not sure why that is a problem. Clearly, there is no *requirement* to take over feature, and there is certainly no reference to syntax.

To take some examples, the metadata specified for EPUB3.1 may very well be a good set of metadata that we require for a WP. We may consider the same with the DPUB-ARIA usage (which is part of EPUB3.1). Etc.

**Comment by lrosenthol** [comment]
>I am not sure why that is a problem

To me (and possibly other readers) it implies that EPUB may/will be given greater weight when considering the developing of WP & PWP than may actually happen.

**Comment by iherman** [comment]
I am happy to _add_ other document types whose similar features we may get inspired on.

**Comment by GarthConboy** [comment]
In my mind, WP will want to be a functional (though not compatible) superset of EPUB, while EPUB 4 will be (one of) the "P"s.

**Comment by rickj** [comment]
> To me (and possibly other readers) it implies that EPUB may/will be given greater weight when considering the developing of WP & PWP than may actually happen.

As a result of the IDPF 'merger', EPUB must specifically be given consideration (of some weight).   As @iherman said above, the decision to give consideration of features from other document types should be part of the conversation, but that does not change the explicit discussion that must happen around EPUB.

**Comment by lrosenthol** [comment]
@rickj 

> As a result of the IDPF 'merger', EPUB must specifically be given consideration (of some weight)

Of course.  In fact, the draft charter includes the fact that in addition to delivering on (P)WP, there is also a separate work item to deliver EPUB 4 (a profile of PWP).  This implies (to me) that PWP will support any/all requirements that EPUB 4 needs in the foundational layers.   

But EPUB 4 doesn't necessary get any greater weight than any other profile of (P)WP might.  Each profile will have requirements and the WG will determine how to address each of them as the technical details are developed.  I would hope that PWP will be flexible enough to produce a number of profiles that address the needs of specific market segments - but that are well aligned.

**Comment by iherman** [comment]
Essentially the same issue as #12. Leaving this issue open to keep the discussion thread, but they should be closed, eventually, together.

**Comment by whmccoy** [comment]
We should distinguish between functional compatibility with EPUB 3 (e.g. since EPUB 3 has a feature to synchronize prerecorded audio and text rendering, Media Overlays then EPUB 4 should have such a feature with a superset of functionality) and strict compatibility (EPUB 4's feature should if possible *be* EPUB 3 Media Overlays). I see the latter as more of a nice-to-have and to be subordinated to the goal of (P)WP to be fully aligned with the modern Open Web Platform. E.g. if the new Media Overlays is based on JSON that would be consistent with the functional compatibility requirement. And the fact that the baseline (P)WP spec may not define a specific Media Overlays "like" feature is exactly why we will need an EPUB 4 to achieve this functional compatibility.

**Comment by GarthConboy** [comment]
Should be closed per resolution resolution to issue #12 -- @lrosenthol concept of Profiles maintained.

**Comment by iherman** [comment]
There is a PR (https://github.com/w3c/dpubwg-charter/pull/31) now for #12; closing this issue.
