### ISSUE TITLE
Definition of the WP spec needs work

### ISSUE THREAD

**Issue by lrosenthol** [w3c/dpubwg-charter#9]
The current statement is (an incorrect) definition of a WP rather than a description of what the specification is trying to accomplish.

**Comment by iherman** [comment]
Can you be more specific? What I did was to simply take over the text from the PWP draft.

That being said, we may want to postpone solving this issue until we have a (more) final text in the PWP draft. The two should be consistent imho.

**Comment by lrosenthol** [comment]
Yes I think simply postponing is the best.

**Comment by iherman** [comment]
The changes have now been agreed upon in the IG, and are now part of the charter, too.
